######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 18 14:30:18 2009
######################################################################

TEMPLATE = app
TARGET = diroperations_test
DEPENDPATH += .
INCLUDEPATH += . ..

# Input
HEADERS += test.h ../diroperations.h ../progresswidget.h
SOURCES += test.cpp ../diroperations.cpp ../progresswidget.cpp

CONFIG += qt debug
